//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace weatherApp.SRWeather {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Weather", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Weather : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idClimaField;
        
        private System.Nullable<decimal> TemperaturaField;
        
        private System.Nullable<decimal> PrecipitacionField;
        
        private System.Nullable<decimal> HumedadField;
        
        private System.Nullable<decimal> VelocidadVientoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int idClima {
            get {
                return this.idClimaField;
            }
            set {
                if ((this.idClimaField.Equals(value) != true)) {
                    this.idClimaField = value;
                    this.RaisePropertyChanged("idClima");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.Nullable<decimal> Temperatura {
            get {
                return this.TemperaturaField;
            }
            set {
                if ((this.TemperaturaField.Equals(value) != true)) {
                    this.TemperaturaField = value;
                    this.RaisePropertyChanged("Temperatura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<decimal> Precipitacion {
            get {
                return this.PrecipitacionField;
            }
            set {
                if ((this.PrecipitacionField.Equals(value) != true)) {
                    this.PrecipitacionField = value;
                    this.RaisePropertyChanged("Precipitacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<decimal> Humedad {
            get {
                return this.HumedadField;
            }
            set {
                if ((this.HumedadField.Equals(value) != true)) {
                    this.HumedadField = value;
                    this.RaisePropertyChanged("Humedad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<decimal> VelocidadViento {
            get {
                return this.VelocidadVientoField;
            }
            set {
                if ((this.VelocidadVientoField.Equals(value) != true)) {
                    this.VelocidadVientoField = value;
                    this.RaisePropertyChanged("VelocidadViento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SRWeather.WSWeatherSoap")]
    public interface WSWeatherSoap {
        
        // CODEGEN: Generating message contract since element name usuario from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addUsuario", ReplyAction="*")]
        weatherApp.SRWeather.addUsuarioResponse addUsuario(weatherApp.SRWeather.addUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<weatherApp.SRWeather.addUsuarioResponse> addUsuarioAsync(weatherApp.SRWeather.addUsuarioRequest request);
        
        // CODEGEN: Generating message contract since element name usuario from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getDataUsuario", ReplyAction="*")]
        weatherApp.SRWeather.getDataUsuarioResponse getDataUsuario(weatherApp.SRWeather.getDataUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getDataUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<weatherApp.SRWeather.getDataUsuarioResponse> getDataUsuarioAsync(weatherApp.SRWeather.getDataUsuarioRequest request);
        
        // CODEGEN: Generating message contract since element name usuario from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateDataUsuario", ReplyAction="*")]
        weatherApp.SRWeather.updateDataUsuarioResponse updateDataUsuario(weatherApp.SRWeather.updateDataUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateDataUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<weatherApp.SRWeather.updateDataUsuarioResponse> updateDataUsuarioAsync(weatherApp.SRWeather.updateDataUsuarioRequest request);
        
        // CODEGEN: Generating message contract since element name usuario from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteUsuario", ReplyAction="*")]
        weatherApp.SRWeather.deleteUsuarioResponse deleteUsuario(weatherApp.SRWeather.deleteUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<weatherApp.SRWeather.deleteUsuarioResponse> deleteUsuarioAsync(weatherApp.SRWeather.deleteUsuarioRequest request);
        
        // CODEGEN: Generating message contract since element name weather from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addWeather", ReplyAction="*")]
        weatherApp.SRWeather.addWeatherResponse addWeather(weatherApp.SRWeather.addWeatherRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addWeather", ReplyAction="*")]
        System.Threading.Tasks.Task<weatherApp.SRWeather.addWeatherResponse> addWeatherAsync(weatherApp.SRWeather.addWeatherRequest request);
        
        // CODEGEN: Generating message contract since element name getDataWeatherResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getDataWeather", ReplyAction="*")]
        weatherApp.SRWeather.getDataWeatherResponse getDataWeather(weatherApp.SRWeather.getDataWeatherRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getDataWeather", ReplyAction="*")]
        System.Threading.Tasks.Task<weatherApp.SRWeather.getDataWeatherResponse> getDataWeatherAsync(weatherApp.SRWeather.getDataWeatherRequest request);
        
        // CODEGEN: Generating message contract since element name weather from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateDataWeather", ReplyAction="*")]
        weatherApp.SRWeather.updateDataWeatherResponse updateDataWeather(weatherApp.SRWeather.updateDataWeatherRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateDataWeather", ReplyAction="*")]
        System.Threading.Tasks.Task<weatherApp.SRWeather.updateDataWeatherResponse> updateDataWeatherAsync(weatherApp.SRWeather.updateDataWeatherRequest request);
        
        // CODEGEN: Generating message contract since element name deleteDataWeatherResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteDataWeather", ReplyAction="*")]
        weatherApp.SRWeather.deleteDataWeatherResponse deleteDataWeather(weatherApp.SRWeather.deleteDataWeatherRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteDataWeather", ReplyAction="*")]
        System.Threading.Tasks.Task<weatherApp.SRWeather.deleteDataWeatherResponse> deleteDataWeatherAsync(weatherApp.SRWeather.deleteDataWeatherRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addUsuario", Namespace="http://tempuri.org/", Order=0)]
        public weatherApp.SRWeather.addUsuarioRequestBody Body;
        
        public addUsuarioRequest() {
        }
        
        public addUsuarioRequest(weatherApp.SRWeather.addUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class addUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        public addUsuarioRequestBody() {
        }
        
        public addUsuarioRequestBody(string usuario, string nombre, string password) {
            this.usuario = usuario;
            this.nombre = nombre;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public weatherApp.SRWeather.addUsuarioResponseBody Body;
        
        public addUsuarioResponse() {
        }
        
        public addUsuarioResponse(weatherApp.SRWeather.addUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class addUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string addUsuarioResult;
        
        public addUsuarioResponseBody() {
        }
        
        public addUsuarioResponseBody(string addUsuarioResult) {
            this.addUsuarioResult = addUsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDataUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDataUsuario", Namespace="http://tempuri.org/", Order=0)]
        public weatherApp.SRWeather.getDataUsuarioRequestBody Body;
        
        public getDataUsuarioRequest() {
        }
        
        public getDataUsuarioRequest(weatherApp.SRWeather.getDataUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getDataUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        public getDataUsuarioRequestBody() {
        }
        
        public getDataUsuarioRequestBody(string usuario) {
            this.usuario = usuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDataUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDataUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public weatherApp.SRWeather.getDataUsuarioResponseBody Body;
        
        public getDataUsuarioResponse() {
        }
        
        public getDataUsuarioResponse(weatherApp.SRWeather.getDataUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getDataUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getDataUsuarioResult;
        
        public getDataUsuarioResponseBody() {
        }
        
        public getDataUsuarioResponseBody(string getDataUsuarioResult) {
            this.getDataUsuarioResult = getDataUsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateDataUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateDataUsuario", Namespace="http://tempuri.org/", Order=0)]
        public weatherApp.SRWeather.updateDataUsuarioRequestBody Body;
        
        public updateDataUsuarioRequest() {
        }
        
        public updateDataUsuarioRequest(weatherApp.SRWeather.updateDataUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class updateDataUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        public updateDataUsuarioRequestBody() {
        }
        
        public updateDataUsuarioRequestBody(string usuario, string nombre, string password) {
            this.usuario = usuario;
            this.nombre = nombre;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateDataUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateDataUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public weatherApp.SRWeather.updateDataUsuarioResponseBody Body;
        
        public updateDataUsuarioResponse() {
        }
        
        public updateDataUsuarioResponse(weatherApp.SRWeather.updateDataUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class updateDataUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string updateDataUsuarioResult;
        
        public updateDataUsuarioResponseBody() {
        }
        
        public updateDataUsuarioResponseBody(string updateDataUsuarioResult) {
            this.updateDataUsuarioResult = updateDataUsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deleteUsuario", Namespace="http://tempuri.org/", Order=0)]
        public weatherApp.SRWeather.deleteUsuarioRequestBody Body;
        
        public deleteUsuarioRequest() {
        }
        
        public deleteUsuarioRequest(weatherApp.SRWeather.deleteUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class deleteUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        public deleteUsuarioRequestBody() {
        }
        
        public deleteUsuarioRequestBody(string usuario) {
            this.usuario = usuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deleteUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public weatherApp.SRWeather.deleteUsuarioResponseBody Body;
        
        public deleteUsuarioResponse() {
        }
        
        public deleteUsuarioResponse(weatherApp.SRWeather.deleteUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class deleteUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string deleteUsuarioResult;
        
        public deleteUsuarioResponseBody() {
        }
        
        public deleteUsuarioResponseBody(string deleteUsuarioResult) {
            this.deleteUsuarioResult = deleteUsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addWeatherRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addWeather", Namespace="http://tempuri.org/", Order=0)]
        public weatherApp.SRWeather.addWeatherRequestBody Body;
        
        public addWeatherRequest() {
        }
        
        public addWeatherRequest(weatherApp.SRWeather.addWeatherRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class addWeatherRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public weatherApp.SRWeather.Weather weather;
        
        public addWeatherRequestBody() {
        }
        
        public addWeatherRequestBody(weatherApp.SRWeather.Weather weather) {
            this.weather = weather;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addWeatherResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addWeatherResponse", Namespace="http://tempuri.org/", Order=0)]
        public weatherApp.SRWeather.addWeatherResponseBody Body;
        
        public addWeatherResponse() {
        }
        
        public addWeatherResponse(weatherApp.SRWeather.addWeatherResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class addWeatherResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string addWeatherResult;
        
        public addWeatherResponseBody() {
        }
        
        public addWeatherResponseBody(string addWeatherResult) {
            this.addWeatherResult = addWeatherResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDataWeatherRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDataWeather", Namespace="http://tempuri.org/", Order=0)]
        public weatherApp.SRWeather.getDataWeatherRequestBody Body;
        
        public getDataWeatherRequest() {
        }
        
        public getDataWeatherRequest(weatherApp.SRWeather.getDataWeatherRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getDataWeatherRequestBody {
        
        public getDataWeatherRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDataWeatherResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDataWeatherResponse", Namespace="http://tempuri.org/", Order=0)]
        public weatherApp.SRWeather.getDataWeatherResponseBody Body;
        
        public getDataWeatherResponse() {
        }
        
        public getDataWeatherResponse(weatherApp.SRWeather.getDataWeatherResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getDataWeatherResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getDataWeatherResult;
        
        public getDataWeatherResponseBody() {
        }
        
        public getDataWeatherResponseBody(string getDataWeatherResult) {
            this.getDataWeatherResult = getDataWeatherResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateDataWeatherRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateDataWeather", Namespace="http://tempuri.org/", Order=0)]
        public weatherApp.SRWeather.updateDataWeatherRequestBody Body;
        
        public updateDataWeatherRequest() {
        }
        
        public updateDataWeatherRequest(weatherApp.SRWeather.updateDataWeatherRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class updateDataWeatherRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public weatherApp.SRWeather.Weather weather;
        
        public updateDataWeatherRequestBody() {
        }
        
        public updateDataWeatherRequestBody(weatherApp.SRWeather.Weather weather) {
            this.weather = weather;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateDataWeatherResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateDataWeatherResponse", Namespace="http://tempuri.org/", Order=0)]
        public weatherApp.SRWeather.updateDataWeatherResponseBody Body;
        
        public updateDataWeatherResponse() {
        }
        
        public updateDataWeatherResponse(weatherApp.SRWeather.updateDataWeatherResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class updateDataWeatherResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string updateDataWeatherResult;
        
        public updateDataWeatherResponseBody() {
        }
        
        public updateDataWeatherResponseBody(string updateDataWeatherResult) {
            this.updateDataWeatherResult = updateDataWeatherResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteDataWeatherRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deleteDataWeather", Namespace="http://tempuri.org/", Order=0)]
        public weatherApp.SRWeather.deleteDataWeatherRequestBody Body;
        
        public deleteDataWeatherRequest() {
        }
        
        public deleteDataWeatherRequest(weatherApp.SRWeather.deleteDataWeatherRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class deleteDataWeatherRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idClima;
        
        public deleteDataWeatherRequestBody() {
        }
        
        public deleteDataWeatherRequestBody(int idClima) {
            this.idClima = idClima;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteDataWeatherResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deleteDataWeatherResponse", Namespace="http://tempuri.org/", Order=0)]
        public weatherApp.SRWeather.deleteDataWeatherResponseBody Body;
        
        public deleteDataWeatherResponse() {
        }
        
        public deleteDataWeatherResponse(weatherApp.SRWeather.deleteDataWeatherResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class deleteDataWeatherResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string deleteDataWeatherResult;
        
        public deleteDataWeatherResponseBody() {
        }
        
        public deleteDataWeatherResponseBody(string deleteDataWeatherResult) {
            this.deleteDataWeatherResult = deleteDataWeatherResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSWeatherSoapChannel : weatherApp.SRWeather.WSWeatherSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSWeatherSoapClient : System.ServiceModel.ClientBase<weatherApp.SRWeather.WSWeatherSoap>, weatherApp.SRWeather.WSWeatherSoap {
        
        public WSWeatherSoapClient() {
        }
        
        public WSWeatherSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSWeatherSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSWeatherSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSWeatherSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        weatherApp.SRWeather.addUsuarioResponse weatherApp.SRWeather.WSWeatherSoap.addUsuario(weatherApp.SRWeather.addUsuarioRequest request) {
            return base.Channel.addUsuario(request);
        }
        
        public string addUsuario(string usuario, string nombre, string password) {
            weatherApp.SRWeather.addUsuarioRequest inValue = new weatherApp.SRWeather.addUsuarioRequest();
            inValue.Body = new weatherApp.SRWeather.addUsuarioRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.nombre = nombre;
            inValue.Body.password = password;
            weatherApp.SRWeather.addUsuarioResponse retVal = ((weatherApp.SRWeather.WSWeatherSoap)(this)).addUsuario(inValue);
            return retVal.Body.addUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<weatherApp.SRWeather.addUsuarioResponse> weatherApp.SRWeather.WSWeatherSoap.addUsuarioAsync(weatherApp.SRWeather.addUsuarioRequest request) {
            return base.Channel.addUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<weatherApp.SRWeather.addUsuarioResponse> addUsuarioAsync(string usuario, string nombre, string password) {
            weatherApp.SRWeather.addUsuarioRequest inValue = new weatherApp.SRWeather.addUsuarioRequest();
            inValue.Body = new weatherApp.SRWeather.addUsuarioRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.nombre = nombre;
            inValue.Body.password = password;
            return ((weatherApp.SRWeather.WSWeatherSoap)(this)).addUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        weatherApp.SRWeather.getDataUsuarioResponse weatherApp.SRWeather.WSWeatherSoap.getDataUsuario(weatherApp.SRWeather.getDataUsuarioRequest request) {
            return base.Channel.getDataUsuario(request);
        }
        
        public string getDataUsuario(string usuario) {
            weatherApp.SRWeather.getDataUsuarioRequest inValue = new weatherApp.SRWeather.getDataUsuarioRequest();
            inValue.Body = new weatherApp.SRWeather.getDataUsuarioRequestBody();
            inValue.Body.usuario = usuario;
            weatherApp.SRWeather.getDataUsuarioResponse retVal = ((weatherApp.SRWeather.WSWeatherSoap)(this)).getDataUsuario(inValue);
            return retVal.Body.getDataUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<weatherApp.SRWeather.getDataUsuarioResponse> weatherApp.SRWeather.WSWeatherSoap.getDataUsuarioAsync(weatherApp.SRWeather.getDataUsuarioRequest request) {
            return base.Channel.getDataUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<weatherApp.SRWeather.getDataUsuarioResponse> getDataUsuarioAsync(string usuario) {
            weatherApp.SRWeather.getDataUsuarioRequest inValue = new weatherApp.SRWeather.getDataUsuarioRequest();
            inValue.Body = new weatherApp.SRWeather.getDataUsuarioRequestBody();
            inValue.Body.usuario = usuario;
            return ((weatherApp.SRWeather.WSWeatherSoap)(this)).getDataUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        weatherApp.SRWeather.updateDataUsuarioResponse weatherApp.SRWeather.WSWeatherSoap.updateDataUsuario(weatherApp.SRWeather.updateDataUsuarioRequest request) {
            return base.Channel.updateDataUsuario(request);
        }
        
        public string updateDataUsuario(string usuario, string nombre, string password) {
            weatherApp.SRWeather.updateDataUsuarioRequest inValue = new weatherApp.SRWeather.updateDataUsuarioRequest();
            inValue.Body = new weatherApp.SRWeather.updateDataUsuarioRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.nombre = nombre;
            inValue.Body.password = password;
            weatherApp.SRWeather.updateDataUsuarioResponse retVal = ((weatherApp.SRWeather.WSWeatherSoap)(this)).updateDataUsuario(inValue);
            return retVal.Body.updateDataUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<weatherApp.SRWeather.updateDataUsuarioResponse> weatherApp.SRWeather.WSWeatherSoap.updateDataUsuarioAsync(weatherApp.SRWeather.updateDataUsuarioRequest request) {
            return base.Channel.updateDataUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<weatherApp.SRWeather.updateDataUsuarioResponse> updateDataUsuarioAsync(string usuario, string nombre, string password) {
            weatherApp.SRWeather.updateDataUsuarioRequest inValue = new weatherApp.SRWeather.updateDataUsuarioRequest();
            inValue.Body = new weatherApp.SRWeather.updateDataUsuarioRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.nombre = nombre;
            inValue.Body.password = password;
            return ((weatherApp.SRWeather.WSWeatherSoap)(this)).updateDataUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        weatherApp.SRWeather.deleteUsuarioResponse weatherApp.SRWeather.WSWeatherSoap.deleteUsuario(weatherApp.SRWeather.deleteUsuarioRequest request) {
            return base.Channel.deleteUsuario(request);
        }
        
        public string deleteUsuario(string usuario) {
            weatherApp.SRWeather.deleteUsuarioRequest inValue = new weatherApp.SRWeather.deleteUsuarioRequest();
            inValue.Body = new weatherApp.SRWeather.deleteUsuarioRequestBody();
            inValue.Body.usuario = usuario;
            weatherApp.SRWeather.deleteUsuarioResponse retVal = ((weatherApp.SRWeather.WSWeatherSoap)(this)).deleteUsuario(inValue);
            return retVal.Body.deleteUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<weatherApp.SRWeather.deleteUsuarioResponse> weatherApp.SRWeather.WSWeatherSoap.deleteUsuarioAsync(weatherApp.SRWeather.deleteUsuarioRequest request) {
            return base.Channel.deleteUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<weatherApp.SRWeather.deleteUsuarioResponse> deleteUsuarioAsync(string usuario) {
            weatherApp.SRWeather.deleteUsuarioRequest inValue = new weatherApp.SRWeather.deleteUsuarioRequest();
            inValue.Body = new weatherApp.SRWeather.deleteUsuarioRequestBody();
            inValue.Body.usuario = usuario;
            return ((weatherApp.SRWeather.WSWeatherSoap)(this)).deleteUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        weatherApp.SRWeather.addWeatherResponse weatherApp.SRWeather.WSWeatherSoap.addWeather(weatherApp.SRWeather.addWeatherRequest request) {
            return base.Channel.addWeather(request);
        }
        
        public string addWeather(weatherApp.SRWeather.Weather weather) {
            weatherApp.SRWeather.addWeatherRequest inValue = new weatherApp.SRWeather.addWeatherRequest();
            inValue.Body = new weatherApp.SRWeather.addWeatherRequestBody();
            inValue.Body.weather = weather;
            weatherApp.SRWeather.addWeatherResponse retVal = ((weatherApp.SRWeather.WSWeatherSoap)(this)).addWeather(inValue);
            return retVal.Body.addWeatherResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<weatherApp.SRWeather.addWeatherResponse> weatherApp.SRWeather.WSWeatherSoap.addWeatherAsync(weatherApp.SRWeather.addWeatherRequest request) {
            return base.Channel.addWeatherAsync(request);
        }
        
        public System.Threading.Tasks.Task<weatherApp.SRWeather.addWeatherResponse> addWeatherAsync(weatherApp.SRWeather.Weather weather) {
            weatherApp.SRWeather.addWeatherRequest inValue = new weatherApp.SRWeather.addWeatherRequest();
            inValue.Body = new weatherApp.SRWeather.addWeatherRequestBody();
            inValue.Body.weather = weather;
            return ((weatherApp.SRWeather.WSWeatherSoap)(this)).addWeatherAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        weatherApp.SRWeather.getDataWeatherResponse weatherApp.SRWeather.WSWeatherSoap.getDataWeather(weatherApp.SRWeather.getDataWeatherRequest request) {
            return base.Channel.getDataWeather(request);
        }
        
        public string getDataWeather() {
            weatherApp.SRWeather.getDataWeatherRequest inValue = new weatherApp.SRWeather.getDataWeatherRequest();
            inValue.Body = new weatherApp.SRWeather.getDataWeatherRequestBody();
            weatherApp.SRWeather.getDataWeatherResponse retVal = ((weatherApp.SRWeather.WSWeatherSoap)(this)).getDataWeather(inValue);
            return retVal.Body.getDataWeatherResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<weatherApp.SRWeather.getDataWeatherResponse> weatherApp.SRWeather.WSWeatherSoap.getDataWeatherAsync(weatherApp.SRWeather.getDataWeatherRequest request) {
            return base.Channel.getDataWeatherAsync(request);
        }
        
        public System.Threading.Tasks.Task<weatherApp.SRWeather.getDataWeatherResponse> getDataWeatherAsync() {
            weatherApp.SRWeather.getDataWeatherRequest inValue = new weatherApp.SRWeather.getDataWeatherRequest();
            inValue.Body = new weatherApp.SRWeather.getDataWeatherRequestBody();
            return ((weatherApp.SRWeather.WSWeatherSoap)(this)).getDataWeatherAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        weatherApp.SRWeather.updateDataWeatherResponse weatherApp.SRWeather.WSWeatherSoap.updateDataWeather(weatherApp.SRWeather.updateDataWeatherRequest request) {
            return base.Channel.updateDataWeather(request);
        }
        
        public string updateDataWeather(weatherApp.SRWeather.Weather weather) {
            weatherApp.SRWeather.updateDataWeatherRequest inValue = new weatherApp.SRWeather.updateDataWeatherRequest();
            inValue.Body = new weatherApp.SRWeather.updateDataWeatherRequestBody();
            inValue.Body.weather = weather;
            weatherApp.SRWeather.updateDataWeatherResponse retVal = ((weatherApp.SRWeather.WSWeatherSoap)(this)).updateDataWeather(inValue);
            return retVal.Body.updateDataWeatherResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<weatherApp.SRWeather.updateDataWeatherResponse> weatherApp.SRWeather.WSWeatherSoap.updateDataWeatherAsync(weatherApp.SRWeather.updateDataWeatherRequest request) {
            return base.Channel.updateDataWeatherAsync(request);
        }
        
        public System.Threading.Tasks.Task<weatherApp.SRWeather.updateDataWeatherResponse> updateDataWeatherAsync(weatherApp.SRWeather.Weather weather) {
            weatherApp.SRWeather.updateDataWeatherRequest inValue = new weatherApp.SRWeather.updateDataWeatherRequest();
            inValue.Body = new weatherApp.SRWeather.updateDataWeatherRequestBody();
            inValue.Body.weather = weather;
            return ((weatherApp.SRWeather.WSWeatherSoap)(this)).updateDataWeatherAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        weatherApp.SRWeather.deleteDataWeatherResponse weatherApp.SRWeather.WSWeatherSoap.deleteDataWeather(weatherApp.SRWeather.deleteDataWeatherRequest request) {
            return base.Channel.deleteDataWeather(request);
        }
        
        public string deleteDataWeather(int idClima) {
            weatherApp.SRWeather.deleteDataWeatherRequest inValue = new weatherApp.SRWeather.deleteDataWeatherRequest();
            inValue.Body = new weatherApp.SRWeather.deleteDataWeatherRequestBody();
            inValue.Body.idClima = idClima;
            weatherApp.SRWeather.deleteDataWeatherResponse retVal = ((weatherApp.SRWeather.WSWeatherSoap)(this)).deleteDataWeather(inValue);
            return retVal.Body.deleteDataWeatherResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<weatherApp.SRWeather.deleteDataWeatherResponse> weatherApp.SRWeather.WSWeatherSoap.deleteDataWeatherAsync(weatherApp.SRWeather.deleteDataWeatherRequest request) {
            return base.Channel.deleteDataWeatherAsync(request);
        }
        
        public System.Threading.Tasks.Task<weatherApp.SRWeather.deleteDataWeatherResponse> deleteDataWeatherAsync(int idClima) {
            weatherApp.SRWeather.deleteDataWeatherRequest inValue = new weatherApp.SRWeather.deleteDataWeatherRequest();
            inValue.Body = new weatherApp.SRWeather.deleteDataWeatherRequestBody();
            inValue.Body.idClima = idClima;
            return ((weatherApp.SRWeather.WSWeatherSoap)(this)).deleteDataWeatherAsync(inValue);
        }
    }
}
