#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gbdWeather
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="weather")]
	public partial class dbDataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertUser(User instance);
    partial void UpdateUser(User instance);
    partial void DeleteUser(User instance);
    partial void InsertWeather(Weather instance);
    partial void UpdateWeather(Weather instance);
    partial void DeleteWeather(Weather instance);
    #endregion
		
		public dbDataDataContext() : 
				base(global::gbdWeather.Properties.Settings.Default.weatherConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
		
		public System.Data.Linq.Table<Weather> Weathers
		{
			get
			{
				return this.GetTable<Weather>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Users")]
	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idUser;
		
		private string _usuario;
		
		private string _Nombre;
		
		private string _Password;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidUserChanging(int value);
    partial void OnidUserChanged();
    partial void OnusuarioChanging(string value);
    partial void OnusuarioChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    #endregion
		
		public User()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUser", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int idUser
		{
			get
			{
				return this._idUser;
			}
			set
			{
				if ((this._idUser != value))
				{
					this.OnidUserChanging(value);
					this.SendPropertyChanging();
					this._idUser = value;
					this.SendPropertyChanged("idUser");
					this.OnidUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string usuario
		{
			get
			{
				return this._usuario;
			}
			set
			{
				if ((this._usuario != value))
				{
					this.OnusuarioChanging(value);
					this.SendPropertyChanging();
					this._usuario = value;
					this.SendPropertyChanged("usuario");
					this.OnusuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Weather")]
	public partial class Weather : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idClima;
		
		private System.Nullable<decimal> _Temperatura;
		
		private System.Nullable<decimal> _Precipitacion;
		
		private System.Nullable<decimal> _Humedad;
		
		private System.Nullable<decimal> _VelocidadViento;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidClimaChanging(int value);
    partial void OnidClimaChanged();
    partial void OnTemperaturaChanging(System.Nullable<decimal> value);
    partial void OnTemperaturaChanged();
    partial void OnPrecipitacionChanging(System.Nullable<decimal> value);
    partial void OnPrecipitacionChanged();
    partial void OnHumedadChanging(System.Nullable<decimal> value);
    partial void OnHumedadChanged();
    partial void OnVelocidadVientoChanging(System.Nullable<decimal> value);
    partial void OnVelocidadVientoChanged();
    #endregion
		
		public Weather()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idClima", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idClima
		{
			get
			{
				return this._idClima;
			}
			set
			{
				if ((this._idClima != value))
				{
					this.OnidClimaChanging(value);
					this.SendPropertyChanging();
					this._idClima = value;
					this.SendPropertyChanged("idClima");
					this.OnidClimaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Temperatura", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Temperatura
		{
			get
			{
				return this._Temperatura;
			}
			set
			{
				if ((this._Temperatura != value))
				{
					this.OnTemperaturaChanging(value);
					this.SendPropertyChanging();
					this._Temperatura = value;
					this.SendPropertyChanged("Temperatura");
					this.OnTemperaturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Precipitacion", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Precipitacion
		{
			get
			{
				return this._Precipitacion;
			}
			set
			{
				if ((this._Precipitacion != value))
				{
					this.OnPrecipitacionChanging(value);
					this.SendPropertyChanging();
					this._Precipitacion = value;
					this.SendPropertyChanged("Precipitacion");
					this.OnPrecipitacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Humedad", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Humedad
		{
			get
			{
				return this._Humedad;
			}
			set
			{
				if ((this._Humedad != value))
				{
					this.OnHumedadChanging(value);
					this.SendPropertyChanging();
					this._Humedad = value;
					this.SendPropertyChanged("Humedad");
					this.OnHumedadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VelocidadViento", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> VelocidadViento
		{
			get
			{
				return this._VelocidadViento;
			}
			set
			{
				if ((this._VelocidadViento != value))
				{
					this.OnVelocidadVientoChanging(value);
					this.SendPropertyChanging();
					this._VelocidadViento = value;
					this.SendPropertyChanged("VelocidadViento");
					this.OnVelocidadVientoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
